### ISSUE TITLE
One of the commit id might change for a unknown readon

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [stefanhh0/aosp-10#6]
`build-4.9.sh`
```
# qcom: Switch camera to new HAL.
git revert --no-edit a96f3a8e384fcbe569e4526e7aa0d020904adbfb
```
Under `android-10.0.0_r33` branch, the commit title match qcom is
`ba30faeb8d181c43e2b611c8c9e2c5397ec3e609`  
in both `stefanhh0/local_manifests` and `sonyxperiadev/local_manifests`.

The script reports bad object error.  Should I change the commit id?  
I'm changing it and to see if it will be success.

**Comment by stefanhh0** [comment]
Should be fixed with: https://github.com/stefanhh0/aosp-10/commit/00322d88cfe0c25b8cd1eb0f01906229243f6afa
