### ISSUE TITLE
Kernel 4.9 no gapps version?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [stefanhh0/aosp-10#7]
I don't have enough disk space to save two copy of android source code  
after run 4.9.sh, it adds gapps to the source tree 
and can't be used to do a normal build without gapps.
(will build failed with some gapps related error message)

**Comment by stefanhh0** [comment]
I'll introduce a --no-gapps switch with one of the next versions

**Comment by stefanhh0** [comment]
I have just introduced the switch, use `./build-4.9.sh -x`. 

For command line help use: `./build-4.9.sh -h`
